whiteboard_prompt_template = """Premium minimal whiteboard marker illustration on one flat off-white paper background (#F6F1E3). Dark charcoal marker linework, warm orange accent (#CD6441) used sparingly. Clean editorial composition, lots of negative space, faceless round-headed human figure when a person is useful, conceptual rather than literal, simple background. The overall mood is restrained, lucid, and emotionally calm. Keep the whole series visually consistent.

Picture first, text last. The image must read as a simple hand-drawn illustration, not a text card, poster, slide, UI, worksheet, or infographic. Use visible text only if the scene prompt explicitly lists optional marker notes. If the notes value is "none", draw absolutely no readable text, no titles, no headings, no labels, and no random characters. If notes are listed, use at most 2 tiny marker annotations, each 8 characters or fewer, placed as small supporting details. Never copy narration/context into the image. Never draw paragraphs, subtitle-like lines, dense labels, menu text, page headers, poster typography, boxed captions, or decorative lettering.

Human and character style: every human figure must be abstract and anonymous: a blank circular head, no face, no eyes, no nose, no mouth, no hair, no ears, no skin tone, no hairstyle, no realistic identity, no detailed clothing. Use simple round-head outline figures only. AI agents and robots should be simple geometric whiteboard symbols, not cute mascots with expressive faces, unless the scene explicitly requires emotion.

Text style for the rare allowed notes only: neat premium whiteboard marker handwriting, confident and slightly organic, adult and understated, drawn by the same marker as the illustration. Not childish, not calligraphy, not brush script, not bubble letters. If precise text is difficult, omit the text completely.

Strict background rule: one mathematically flat, uniform #F6F1E3 paper tone edge-to-edge. The background must have no tonal variation at all: no white glow, no light bloom, no paper wash, no watercolor wash, no smudged paper texture, no lighting effect, no local light patches, no gradient, no vignette, no shadow blocks, no cloudy patches, no beige-white contrast halos around drawings. Do not use brighter white or darker beige areas to imply sunlight, space, heat, depth, or atmosphere; express those ideas only with marker lines and sparse orange accents. No realism, no 3D, no painterly texture, no high saturation, no complex scene, no photographic detail.
"""
